name: Deploy to Firebase App Distribution

on:
  workflow_dispatch:
    inputs:
      release_notes:
        type: string
        reuired: true
        default: 'Android Debug Build'

jobs:
  build:
    name: Android Debug Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: build debug
        run: ./gradlew assembleDebug
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: QA
          file: app/build/outputs/apk/debug/app-debug.apk