name: Deploy to Firebase App Distribution
'on':
  workflow_dispatch:
    inputs:
      release_notes:
        type: string
        reuired: true
        default: Android Debug Build
        description: Release Notes
jobs:
  build:
    name: Android Debug Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: '11'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: build debug
        run: ./gradlew assembleDebug

      - name: Upload build to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: '${{ secrets.FIREBASE_APP_ID }}'
          serviceCredentialsFileContent: '${{ secrets.CREDENTIAL_FILE_CONTENT }}'
          groups: QA
          file: app/build/outputs/apk/debug/app-debug.apk